# Generated by Django 5.2.11 on 2026-02-24 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')]),
        ),
    ]
