# Generated by Django 5.2.11 on 2026-02-25 07:47

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Разрешены только файлы JPG, JPEG, PNG и WEBP.'), accounts.models.validate_avatar_file_size]),
        ),
    ]
