# Generated by Django 5.2.11 on 2026-02-24 22:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('min_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
            ],
            options={
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('city', models.CharField(default='Алматы', max_length=120)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('capacity', models.PositiveSmallIntegerField(default=80)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='catalog.cinema')),
                ('format_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='catalog.formattype')),
            ],
            options={
                'ordering': ['cinema__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HallAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls_link', to='catalog.amenity')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities_link', to='catalog.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, unique=True)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('original_title', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField()),
                ('poster_url', models.URLField(blank=True)),
                ('duration_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('now', 'В прокате'), ('soon', 'Скоро')], default='now', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='catalog.agerating')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='catalog.country')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='catalog.genre')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='catalog.language')),
            ],
            options={
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='catalog.country')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_items', to='catalog.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_items', to='catalog.person')),
            ],
            options={
                'ordering': ['movie', 'position', 'person__full_name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movies', through='catalog.MovieCast', to='catalog.person'),
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('run_from', models.DateField()),
                ('run_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='catalog.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='catalog.movie')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studios', to='catalog.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='catalog.studio'),
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_prices', to='catalog.ticketcategory')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_prices', to='catalog.movie')),
            ],
            options={
                'ordering': ['movie__title', 'category__title'],
            },
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('cinema', 'name'), name='unique_hall_name_per_cinema'),
        ),
        migrations.AddConstraint(
            model_name='hallamenity',
            constraint=models.UniqueConstraint(fields=('hall', 'amenity'), name='unique_amenity_per_hall'),
        ),
        migrations.AddConstraint(
            model_name='moviecast',
            constraint=models.UniqueConstraint(fields=('movie', 'person'), name='unique_person_per_movie_cast'),
        ),
        migrations.AddConstraint(
            model_name='screening',
            constraint=models.UniqueConstraint(fields=('hall', 'start_at'), name='unique_hall_screening_time'),
        ),
        migrations.AddConstraint(
            model_name='ticketprice',
            constraint=models.UniqueConstraint(fields=('movie', 'category'), name='unique_ticket_price_per_category'),
        ),
    ]
